---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
---

## Orchestrating multi-state QTL analysis with R

**Key findings:**

* A new approach for exploring multi-state QTL summary statistics in R.
* QTLExperiment introduces a container object for storing QTL summary statistics, including effect sizes and standard errors. The QTLExperiment class is an S4 object built upon the SummarizedExperiment object class. The QTLExperiment package includes functions to filter, combine and subset QTLExperiment objects. 
* multistateQTL includes functions to simulate, analyse, and visualise multi-state QTL data. 

**Abstract**

The scope of many Quantitative Trait Loci (QTL) mapping studies has increased to include different cellular and environmental states. However, drawing biologically relevant conclusions from the large, high-dimensional data that come from multi-state QTL mapping studies is not straightforward.

To address this problem, we introduce two R packages, QTLExperiment and multistateQTL. The QTLExperiment package provides a robust container for storing and manipulating QTL summary statistics and associated metadata. The multistateQTL package provides tools to facilitate the analysis of multi-state QTL data stored in a QTLExperiment container. This package provides methods for statistical analysis, quantification of sharing, classification of multi-state QTL associations, visualization of the data, and more. It also provides flexible methods for simulating multi-state QTL summary statistics with user-defined properties.

The packages QTLExperiment and multistateQTL are available on Bioconductor (https://www.bioconductor.org/packages/QTLExperiment and https://bioconductor.org/packages/multistateQTL).

## Authors

The full author list is as follows:

Christina B. Del Azodi<sup>1,2,#</sup>, Amelia M. Dunstone<sup>1,2</sup>, Davis J. McCarthy<sup>1,2#</sup>

<sup>1</sup>St Vincent’s Institute of Medical Research, Fitzroy, Victoria 3065, Australia. 

<sup>2</sup>University of Melbourne, Parkville, Victoria 3052, Australia. 

<sup>#</sup> Corresponding authors. 

